In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os 
import warnings
warnings.filterwarnings("ignore", category=DeprecationWarning) 
# For NN implemetation using Sklearn
from sklearn.neural_network import MLPClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
#from tabulate import tabulate
import sklearn.metrics as metrics

In [3]:
os.chdir('/Users/gopalrao000/Desktop/Bhargavi/Fall-22/ML/HW3') 
data=pd.read_csv("Titanic.csv")
print("dimentions",data.shape)
data.head()

dimentions (1309, 15)


Unnamed: 0 pclass  survived                             name     sex  \
0           1    1st         1    Allen, Miss. Elisabeth Walton  female   
1           2    1st         1   Allison, Master. Hudson Trevor    male   
2           3    1st         0     Allison, Miss. Helen Loraine  female   
3           4    1st         0  Allison, Mr. Hudson Joshua Crei    male   
4           5    1st         0  Allison, Mrs. Hudson J C (Bessi  female   

       age  sibsp  parch  ticket        fare    cabin     embarked boat  \
0  29.0000      0      0   24160  211.337494       B5  Southampton    2   
1   0.9167      1      2  113781  151.550003  C22 C26  Southampton   11   
2   2.0000      1      2  113781  151.550003  C22 C26  Southampton  NaN   
3  30.0000      1      2  113781  151.550003  C22 C26  Southampton  NaN   
4  25.0000      1      2  113781  151.550003  C22 C26  Southampton  NaN   

    body                        home.dest  
0    NaN                     St Louis, MO  
1    NaN  Montreal, PQ / Chesterville, ON  
2    NaN  Montreal, PQ / Chesterville, ON  
3  135.0  Montreal, PQ / Chesterville, ON  
4    NaN  Montreal, PQ / Chesterville, ON

In [4]:
data["survived"] = data["survived"].astype('category')

In [5]:
# checking column types
result = data.dtypes

print("Columns and their data type:")
print(result)

Columns and their data type:
Unnamed: 0       int64
pclass          object
survived      category
name            object
sex             object
age            float64
sibsp            int64
parch            int64
ticket          object
fare           float64
cabin           object
embarked        object
boat            object
body           float64
home.dest       object
dtype: object


In [6]:
check_null_values=data.isnull().sum(axis=0)
check_null_values

Unnamed: 0       0
pclass           0
survived         0
name             0
sex              0
age            263
sibsp            0
parch            0
ticket           0
fare             1
cabin         1014
embarked         2
boat           823
body          1188
home.dest      564
dtype: int64

In [7]:
# can use mode as well
#Fill in n/a attributes with the average of the same attributes from other training examples.
data["age"] = data["age"].fillna(value=data["age"].mean())
data["fare"] = data["fare"].fillna(value=data["fare"].mean())
data["cabin"] = data["cabin"].fillna(value=data["cabin"].value_counts().idxmax())
data["embarked"] = data["embarked"].fillna(value=data["embarked"].value_counts().idxmax())
data["boat"] = data["boat"].fillna(value=data["boat"].value_counts().idxmax())
data["body"] = data["body"].fillna(value=data["body"].mean())
data["home.dest"] = data["home.dest"].fillna(value=data["home.dest"].value_counts().idxmax())


In [8]:
check_null_values=data.isnull().sum(axis=0)
check_null_values

Unnamed: 0    0
pclass        0
survived      0
name          0
sex           0
age           0
sibsp         0
parch         0
ticket        0
fare          0
cabin         0
embarked      0
boat          0
body          0
home.dest     0
dtype: int64

# Step 1: use our “titanic” dataset in homework #3, and split data in the same way you did in homework #3 – 80% as training and 20% test sets; 

In [9]:
from sklearn.model_selection import train_test_split
train, test = train_test_split(data, test_size=0.2)

In [10]:
#Fit a neural network using independent variables ‘pclass + sex + age + sibsp’ and dependent variable ‘survived.
x_train=train[['pclass','sex','age','sibsp']]
y_train=train[['survived']]
x_test=test[['pclass','sex','age','sibsp']]
y_test=test[['survived']]

In [11]:
x_train =pd.get_dummies(x_train)
x_test =pd.get_dummies(x_test)
x_train.head()


age  sibsp  pclass_1st  pclass_2nd  pclass_3rd  sex_female  \
1284  29.881135      0           0           0           1           0   
304   60.000000      1           1           0           0           1   
934    4.000000      0           0           0           1           1   
571   23.000000      0           0           1           0           0   
907   20.000000      1           0           0           1           1   

      sex_male  
1284         1  
304          0  
934          0  
571          1  
907          0

In [12]:
y_train.head()

survived
1284        0
304         1
934         1
571         0
907         0

# Step 2: Fit a neural network using independent variables ‘pclass + sex + age + sibsp’ and dependent variable ‘survived’. Fill in n/a attributes with the average of the same attributes from other training examples. Use 2 hidden layers and set the activation functions for both the hidden and output layer to be the sigmoid function. Set “solver” parameter as either SGD (stochastic gradient descend) or Adam (similar to SGD but optimized performance with mini batches). You can adjust parameter “alpha” for regularization (to control overfitting) and other parameters such as “learning rate” and “momentum” as needed.   

In [34]:
# Use 2 hidden layers and set the activation functions 
# for both the hidden and output layer to be the sigmoid function 

# Sigmoid function is same as Logestic function-so used logestic in MLP
#( In MLP of scikit- sigmoid activation is not available only logestic)


# Solver used is 'Adam' as it is giving better accuracy than SGD()
# initialised alpha (regularization parameter) and momentum parameter 
# max_iter = epoch is: 1000
clf1 = MLPClassifier(hidden_layer_sizes = (10, 5), 
                    activation="logistic", 
                    solver="adam", 
                    alpha =1e-5, 
                    momentum = 0.1,
                    max_iter = 1000, 
                    verbose=True) 

In [14]:
clf1.fit(x_train,y_train)

/Users/gopalrao000/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


Iteration 1, loss = 0.83806907
Iteration 2, loss = 0.83028348
Iteration 3, loss = 0.82258897
Iteration 4, loss = 0.81540174
Iteration 5, loss = 0.80820209
Iteration 6, loss = 0.80136475
Iteration 7, loss = 0.79467574
Iteration 8, loss = 0.78800684
Iteration 9, loss = 0.78155531
Iteration 10, loss = 0.77523057
Iteration 11, loss = 0.76884416
Iteration 12, loss = 0.76256244
Iteration 13, loss = 0.75648594
Iteration 14, loss = 0.75008446
Iteration 15, loss = 0.74397713
Iteration 16, loss = 0.73793554
Iteration 17, loss = 0.73194903
Iteration 18, loss = 0.72634807
Iteration 19, loss = 0.72132771
Iteration 20, loss = 0.71646583
Iteration 21, loss = 0.71197711
Iteration 22, loss = 0.70773921
Iteration 23, loss = 0.70416551
Iteration 24, loss = 0.70027775
Iteration 25, loss = 0.69702753
Iteration 26, loss = 0.69370139
Iteration 27, loss = 0.69107933
Iteration 28, loss = 0.68852437
Iteration 29, loss = 0.68637622
Iteration 30, loss = 0.68429367
Iteration 31, loss = 0.68249734
Iteration 32, los

MLPClassifier(activation='logistic', alpha=1e-05, hidden_layer_sizes=(10, 5),
              max_iter=1000, momentum=0.1, verbose=True)

In [15]:
predict1=clf1.predict(x_test)
print(metrics.accuracy_score(y_test,predict1))
print(confusion_matrix(y_test,predict1))
print(classification_report(y_test, predict1))

0.8015267175572519
[[145  21]
 [ 31  65]]
              precision    recall  f1-score   support

           0       0.82      0.87      0.85       166
           1       0.76      0.68      0.71        96

    accuracy                           0.80       262
   macro avg       0.79      0.78      0.78       262
weighted avg       0.80      0.80      0.80       262



# Step 3: Check the performance of the model with out-of- sample accuracy, defined as  

out-of-sample percent survivors correctly predicted (on test set)  :68

out-of-sample percent fatalities correctly predicted (on test set) :87

Accuracy: 80%

# try two different network structures (i.e., number of neurons at each hidden layer) and show their respective accuracy.  

# Model2

In [20]:
clf2 = MLPClassifier(hidden_layer_sizes = (100 ,50), 
                    activation="logistic", 
                    solver="adam", 
                    alpha =1e-5, 
                    momentum = 0.1,
                    max_iter = 5000, 
                    verbose=True) 

In [21]:
clf2.fit(x_train,y_train)

/Users/gopalrao000/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


Iteration 1, loss = 0.66622674
Iteration 2, loss = 0.66492234
Iteration 3, loss = 0.66397580
Iteration 4, loss = 0.66270777
Iteration 5, loss = 0.66183279
Iteration 6, loss = 0.66038915
Iteration 7, loss = 0.66119166
Iteration 8, loss = 0.65819523
Iteration 9, loss = 0.65703558
Iteration 10, loss = 0.65552779
Iteration 11, loss = 0.65657685
Iteration 12, loss = 0.65224514
Iteration 13, loss = 0.64916616
Iteration 14, loss = 0.64619476
Iteration 15, loss = 0.64269131
Iteration 16, loss = 0.63884332
Iteration 17, loss = 0.63503658
Iteration 18, loss = 0.63273060
Iteration 19, loss = 0.62283301
Iteration 20, loss = 0.61916255
Iteration 21, loss = 0.61045816
Iteration 22, loss = 0.60268295
Iteration 23, loss = 0.59271025
Iteration 24, loss = 0.58227248
Iteration 25, loss = 0.57018448
Iteration 26, loss = 0.55942631
Iteration 27, loss = 0.54647086
Iteration 28, loss = 0.53387349
Iteration 29, loss = 0.52293539
Iteration 30, loss = 0.51162842
Iteration 31, loss = 0.50339751
Iteration 32, los

MLPClassifier(activation='logistic', alpha=1e-05, hidden_layer_sizes=(100, 50),
              max_iter=5000, momentum=0.1, verbose=True)

In [22]:
predict2=clf2.predict(x_test)
print(metrics.accuracy_score(y_test,predict2))
print(confusion_matrix(y_test,predict2))
print(classification_report(y_test, predict2))

0.816793893129771
[[147  19]
 [ 29  67]]
              precision    recall  f1-score   support

           0       0.84      0.89      0.86       166
           1       0.78      0.70      0.74        96

    accuracy                           0.82       262
   macro avg       0.81      0.79      0.80       262
weighted avg       0.81      0.82      0.81       262



out-of-sample percent survivors correctly predicted (on test set)  :70

out-of-sample percent fatalities correctly predicted (on test set) :89

Accuracy: 82%

# Third Model

In [23]:
clf3 = MLPClassifier(hidden_layer_sizes = (150 ,75), 
                    activation="logistic", 
                    solver="adam", 
                    alpha =1e-5, 
                    momentum = 0.1,
                    max_iter = 5000, 
                    verbose=True) 

In [24]:
clf3.fit(x_train,y_train)

/Users/gopalrao000/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


Iteration 1, loss = 0.67492822
Iteration 2, loss = 0.67397571
Iteration 3, loss = 0.66619482
Iteration 4, loss = 0.66511189
Iteration 5, loss = 0.66305767
Iteration 6, loss = 0.66216274
Iteration 7, loss = 0.65938885
Iteration 8, loss = 0.65840582
Iteration 9, loss = 0.65556847
Iteration 10, loss = 0.65468354
Iteration 11, loss = 0.65032977
Iteration 12, loss = 0.64839677
Iteration 13, loss = 0.64344349
Iteration 14, loss = 0.63842551
Iteration 15, loss = 0.63224261
Iteration 16, loss = 0.62547810
Iteration 17, loss = 0.61691044
Iteration 18, loss = 0.60680376
Iteration 19, loss = 0.59344851
Iteration 20, loss = 0.58193494
Iteration 21, loss = 0.56646187
Iteration 22, loss = 0.55169548
Iteration 23, loss = 0.53466921
Iteration 24, loss = 0.52118985
Iteration 25, loss = 0.50956403
Iteration 26, loss = 0.49640966
Iteration 27, loss = 0.49104996
Iteration 28, loss = 0.47991575
Iteration 29, loss = 0.47590376
Iteration 30, loss = 0.47062693
Iteration 31, loss = 0.47273071
Iteration 32, los

MLPClassifier(activation='logistic', alpha=1e-05, hidden_layer_sizes=(150, 75),
              max_iter=5000, momentum=0.1, verbose=True)

In [26]:
predict3=clf3.predict(x_test)
print(metrics.accuracy_score(y_test,predict3))
print(confusion_matrix(y_test,predict3))
print(classification_report(y_test, predict3))

0.816793893129771
[[147  19]
 [ 29  67]]
              precision    recall  f1-score   support

           0       0.84      0.89      0.86       166
           1       0.78      0.70      0.74        96

    accuracy                           0.82       262
   macro avg       0.81      0.79      0.80       262
weighted avg       0.81      0.82      0.81       262



out-of-sample percent survivors correctly predicted (on test set)  :70

out-of-sample percent fatalities correctly predicted (on test set) :89

Accuracy: 82%


So after incrasing hidden layers size using ADM , accuracy score improved.
But after certain stage there is no improvement even if we keep on increasing hidden layer size.

# Step 4: Compare the out-of-sample accuracy (as defined in step 3) with the random forest obtained in homework #3. (You can either use a table or plot the results of the two algorithms in one figure). Explain any difference in accuracy.

In [29]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import make_classification
import sklearn.metrics as metrics

In [30]:
forest = RandomForestClassifier(n_estimators=50,max_leaf_nodes = 10)

In [31]:
# here changed the y_train to A column-vector y was passed when a 1d array was expected

forest.fit(x_train,y_train.values.ravel())  

RandomForestClassifier(max_leaf_nodes=10, n_estimators=50)

In [32]:
predicted_forest = forest.predict(x_test)

In [33]:
print(metrics.accuracy_score(y_test,predicted_forest))
print(confusion_matrix(y_test,predicted_forest))
print(classification_report(y_test,predicted_forest))

0.8015267175572519
[[141  25]
 [ 27  69]]
              precision    recall  f1-score   support

           0       0.84      0.85      0.84       166
           1       0.73      0.72      0.73        96

    accuracy                           0.80       262
   macro avg       0.79      0.78      0.79       262
weighted avg       0.80      0.80      0.80       262



from HW3- random forest model accuracy with bestparameters is 80%. 
While with nural network Accuracy increased to 82%. With increase in nodes in hidden layers accuracy increased by 2%
So neural network helped to improve accuracy of the prediction for this problem compared to random forest. by just 2%